# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build PDF, ePub & HTMLZip
formats: all

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true